# Generated by Django 2.2.6 on 2019-10-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resort',
            fields=[
                ('resort_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('resort_desc', models.CharField(max_length=25, null=True)),
                ('transfer_reversal', models.CharField(max_length=3, null=True)),
                ('active', models.CharField(max_length=3, null=True)),
            ],
            options={
                'db_table': 'Resorts',
            },
        ),
    ]
